default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  socket: /var/run/mysqld/mysqld.sock
  username: <%= Rails.application.credentials.dig(:database_username) %>
  password: <%= Rails.application.credentials.dig(:database_password) %>
  host: <%= Rails.application.credentials.dig(:database_host) %>

development:
  <<: *default
  database: relate_development

test:
  <<: *default
  database: relate

production:
  <<: *default
  database: relate



